packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "app-ami-${local.timestamp}"
  instance_type = "t2.micro"
  region        = "eu-central-1"
  source_ami    = "ami-0a485299eeb98b979"
  ssh_username  = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo yum update -y", "sudo yum install -y httpd pip git httpd-devel python3-devel", "sudo ln -s /usr/bin/python3 /usr/bin/python"]
  }

  provisioner "file" {
    destination = "/tmp/stock_app"
    source      = "./stock_app"
  }

  provisioner "file" {
    destination = "/tmp/flask.conf"
    source      = "./flask.conf"
  }

  provisioner "shell" {
    inline = ["sudo mv /tmp/flask.conf /etc/httpd/conf.d/flask.conf", "sudo mv /tmp/stock_app /stock_app", "python -m venv /stock_app/flask", "source /stock_app/flask/bin/activate", "pip install -r /stock_app/requirements.txt", "sudo systemctl enable httpd"]
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
  }
}
