version: 2.1

jobs:
  apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply Green ec2 and switch traffic
          command: |
            terraform init -input=false
            packer build app-ami.json
            source parsing.sh
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_traffic:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test traffic
          command: |
            curl http://example-elb-2021166317.eu-central-1.elb.amazonaws.com/test
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  switch:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: update blue ami
          command: |
            export TF_VAR_old_blue_ami_id="$TF_VAR_blue_ami_id"
            export TF_VAR_blue_ami_id="$TF_VAR_green_ami_id"
            export TF_VAR_active_deployment="blue"
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .
              
  remove:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: remove green ami 
          command: |
            export TF_VAR_is_green_active=false
            terraform apply -auto-approve
            aws ec2 deregister-image --image-id $TF_VAR_old_blue_ami_id
      - persist_to_workspace:
          root: .
          paths:
            - .

workflow:
  version: 2
  plan_blue_green_strategy:
    jobs:
      - apply:
          filters:
            branches:
              only: main
      - test:
          filters:
            branches:
              only: main
      - switch:
          filters:
            branches:
              only: main
      - test:
          filters:
            branches:
              only: main
      - remove:
          filters:
            branches:
              only: main
