version: 2.1

jobs:
  apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply Green ec2 and switch traffic
          command: |
            apt install gpg
            terraform init -input=false
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
            apt install packer
            packer build app-ami.json
            source parsing.sh
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  test1:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test traffic
          command: |
            curl http://example-elb-2021166317.eu-central-1.elb.amazonaws.com/test
      - persist_to_workspace:
          root: .
          paths:
            - .

  test2:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test traffic
          command: |
            curl http://example-elb-2021166317.eu-central-1.elb.amazonaws.com/test
      - persist_to_workspace:
          root: .
          paths:
            - .

  switch:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: update blue ami
          command: |
            export TF_VAR_old_blue_ami_id="$TF_VAR_blue_ami_id"
            export TF_VAR_blue_ami_id="$TF_VAR_green_ami_id"
            export TF_VAR_active_deployment="blue"
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  remove:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: remove green ami
          command: |
            export TF_VAR_is_green_active=false
            terraform apply -auto-approve
            aws ec2 deregister-image --image-id $TF_VAR_old_blue_ami_id

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - apply:
          filters:
            branches:
              only: main
      - test1:
          requires:
            - apply
          filters:
            branches:
              only: main
      - switch:
          requires:
            - test1
          filters:
            branches:
              only: main
      - test2:
          requires:
            - switch
          filters:
            branches:
              only: main
      - remove:
          requires:
            - test2
          filters:
            branches:
              only: main